#ifndef C_P2P_CHAT_CONFIG_H
#define C_P2P_CHAT_CONFIG_H

#define TICK_PER_SECOND 10
#define SEND_PING_PAUSE 10
#define PING_SKIP_TO_TIMEOUT 10

#define BUFLEN 512
#define MAX_CLIENTS 20
#define DEFAULT_PORT 8888
#define MAX_NAME_LENGTH 13

#endif